---
# Fix missing end of file new_line

- name: "[MISSING NEWLINE] check the last line of file"
  shell:
    cmd: tail -1 {{ _current_file }}
  changed_when: false
  register: _result
  failed_when: _result.stdout | length > 1
  ignore_errors: true

- name: "[MISSING NEWLINE] add newline"
  lineinfile:
    path: "{{ _current_file }}"
    line: ' '
    insertafter: EOF
  when: _result.stdout | length > 1

- name: "[MISSING NEWLINE] add newline"
  lineinfile:
    path: "{{ _current_file }}"
    line: ' '
    insertafter: EOF
  when: _result.stdout | length > 1
  
- name: "[MISSING NEWLINE] add newline"
  lineinfile:
    path: "{{ _current_file }}"
    line: ' '
    insertafter: EOF
  when: _result.stdout | length > 1

- name: "[MISSING NEWLINE] check the last line of file"
  shell: 
    cmd: tail -1 {{ _current_file }}
  register: _result
  changed_when: false
  failed_when: _result.stdout | length > 1
  ignore_errors: true
