---

- name: GET FILES THAT MUST BE FIXED
  find:
    paths: "{{ fix_directories }}"
    patterns: "{{ files_pattern }}"
    recurse: true
    use_regex: "{{ use_regex }}"
  register: _fix_files 

# - name: Correct end of file newline
#   include_tasks: 
#     file: EOF_space_1.yml

- name: Correct trailling spaces
  include_tasks: 
    file: EOL_space.yml

- name: Correct missing ---
  include_tasks: 
    file: three_dashes_1.yml

- name: Correct missing comment spaces
  include_tasks: 
    file: comment_space.yml

- name: Replace yes/no for true/false
  include_tasks: 
    file: yes_to_true.yml

- name: Erase blank spaces
  include_tasks:
    file: blank_lines_1.yml

- name: Correct spaces before and after commas
  include_tasks:
    file: comma_spaces.yml

- name: Correct spaces after hyphen
  include_tasks:
    file: hyphen_spaces.yml

- name: Correct spaces between brackets
  include_tasks:
    file: brackets_spaces.yml

- name: Correct fake spaces
  include_tasks:
    file: fake_spaces.yml

# - name: Divide long lines
#   include_tasks:
#     file: long_lines.yml